### ISSUE TITLE
JavaでopenCVを扱えるようにする

### ISSUE THREAD

**Issue by TakanariKida** [Miyabi-OKLAB/ComputerVision#1]

**Comment by TakanariKida** [comment]
自分は“CPad for Java2 SDK”を用いてopenCV3.0.0を扱えるようにしました．
インストール関連は比較的簡単でした．
今後，このようなソフトウェアは使う機会も多くなってくると思うのでインストールガイドや使い方などをまとめたものを作った方が良さそうですね…

**Comment by IShuhei** [comment]
こちらはeclipseで同様のOpenCV3.0.0を扱えるようにしました．
こちらも比較的インストールは簡単で，外部jarの設定に一度頭をひねったぐらいですみました．

**Comment by TakanariKida** [comment]
了解です
二人とも出来てるようですね
